/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary": "rgb(var(--primary-rgb) / <alpha-value>)",
        "secondary": "rgb(var(--secondary-rgb) / <alpha-value>)",
        "secondary-fixed": "var(--secondary-dim)",
        "surface-variant": "rgb(var(--surface-variant-rgb) / <alpha-value>)",
        "surface-dim": "var(--surface-dim)",
        "primary-dim": "var(--primary-dim)",
        "tertiary-dim": "var(--tertiary-dim)",
        "primary-fixed": "var(--primary)",
        "tertiary-container": "var(--tertiary-container)",
        "outline": "rgb(var(--outline-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant-rgb) / <alpha-value>)",
        "on-primary": "var(--on-primary)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-secondary": "var(--on-secondary)",
        "on-tertiary-fixed": "var(--on-tertiary-container)",
        "surface-tint": "var(--primary)",
        "tertiary-fixed-dim": "var(--tertiary-dim)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "background": "var(--background)",
        "on-secondary-fixed-variant": "var(--on-secondary-container)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-container)",
        "on-tertiary": "var(--on-tertiary)",
        "surface-container-low": "var(--surface-container-low)",
        "on-primary-fixed": "var(--on-primary-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "surface": "var(--surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "secondary-dim": "var(--secondary-dim)",
        "secondary-container": "var(--secondary-container)",
        "on-surface": "var(--on-surface)",
        "on-error-container": "var(--on-error-container)",
        "error": "var(--error)",
        "on-error": "var(--on-error)",
        "surface-bright": "var(--surface-bright)",
        "on-primary-container": "var(--on-primary-container)",
        "secondary-fixed-dim": "var(--secondary-dim)",
        "on-primary-fixed-variant": "var(--on-primary-container)",
        "inverse-surface": "var(--inverse-surface)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-secondary-fixed": "var(--on-secondary)",
        "primary-container": "var(--primary-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container": "var(--surface-container)",
        "inverse-primary": "var(--inverse-primary)",
        "error-dim": "var(--error-dim)",
        "tertiary-fixed": "var(--tertiary-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "primary-fixed-dim": "var(--primary-dim)",
        "on-background": "var(--on-surface)",
        "tertiary": "var(--tertiary)",
        "error-container": "var(--error-container)"
      },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Space Grotesk", "monospace"]
            }
        },
    },
    plugins: [],
}
